baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Stone Fields'

theme = 'classy'
[params]
author='<Stone Fields>'
siteHeading = '< Stone Fields >'
mainSections = ['Home', 'Reviews', 'Writing','Research','Cool Stuff']

[taxonomies]
year = "year"
month = "month"
tags = "tags"
categories = "categories"
