baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Stone Site'

theme = 'classy'
[params]
author='<Stone Fields>'
siteHeading = '< Stone Fields >'
mainSections = ['Home', 'Reviews', 'Writing','Research','Cool Stuff']


[[menu.main]]
 

  name = "Reviews"
  identifier = "Reviews"
  title = "Reviews"
  url = "/Reviews2/"
  weight = 13

[[menu.main]]

  name = "Movies Reviews"
  parent = "Movies"
  title = "Movies Reviews"
  url = "/Reviews2/Movie Reviews/"
  weight = 5  

