baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Stone Site'

theme = 'classy'
googlefonts = “http://fonts.googleapis.com/css?family=Itim|Limelight”
[params]
author='<Stone Fields>'
siteHeading = '<Stone Fields>'
mainSections = ['Home', 'Reviews2', 'Writing','Research','Cool Stuff']
