baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Stone Site'

theme = 'classy'
[params]
author='<Stone Fields>'
siteHeading = '< Stone Fields >'
mainSections = ['Home', 'Reviews', 'Writing','Research','Cool Stuff']


[[menu.main]]
name = "Reviews"
title = "Reviews"
url = "/Reviews2/"
weight = 10

[[menu.main]]
name = "Movie Reviews"
parent = "Reviews"
title = "Movies Reviews"
url = "/Reviews2/Movie Reviews/"
weight = 5

